# Generated by Django 2.0.1 on 2019-05-03 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20190503_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('email', models.CharField(max_length=40)),
                ('contactnum', models.IntegerField()),
                ('egap', models.IntegerField()),
                ('tenper', models.FloatField()),
                ('tenyop', models.IntegerField()),
                ('tweper', models.FloatField()),
                ('tweyop', models.IntegerField()),
                ('regid', models.IntegerField()),
                ('rollno', models.CharField(max_length=20)),
                ('gper', models.FloatField()),
                ('back', models.IntegerField()),
            ],
        ),
    ]
