# Generated by Django 2.0.1 on 2019-05-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('email', models.CharField(max_length=40)),
                ('contactnum', models.IntegerField()),
                ('egap', models.IntegerField()),
                ('tenper', models.FloatField()),
                ('tenyop', models.IntegerField()),
                ('tweper', models.FloatField()),
                ('tweyop', models.IntegerField()),
                ('regid', models.IntegerField()),
                ('rollno', models.CharField(max_length=20)),
                ('gper', models.FloatField()),
                ('back', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='temp',
            name='user',
        ),
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
