# Generated by Django 2.0.1 on 2019-05-03 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20190504_0124'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Temp1',
            new_name='Temp2',
        ),
    ]
