# Generated by Django 2.0.1 on 2019-05-03 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20190504_0141'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='temp2',
            table='post',
        ),
    ]
