# Generated by Django 2.0.1 on 2019-05-04 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20190504_0315'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='temp2',
            table=None,
        ),
    ]
